/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.github.nfalco79.junit4osgi.gui;

import java.awt.Cursor;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.swing.JFrame;
import javax.swing.JScrollBar;
import javax.swing.table.TableColumn;

import org.junit.runner.Description;
import org.junit.runner.JUnitCore;
import org.junit.runner.notification.Failure;
import org.junit.runner.notification.RunListener;

import com.github.nfalco79.junit4osgi.registry.spi.TestBean;
import com.github.nfalco79.junit4osgi.registry.spi.TestRegistry;
import com.github.nfalco79.junit4osgi.registry.spi.TestRegistryChangeListener;
import com.github.nfalco79.junit4osgi.registry.spi.TestRegistryEvent;

/**
 * Swing Runner for JUnit4OSGi registry.
 */
public class SwingRunner extends JFrame {

	private static final long serialVersionUID = 1L;

	private TestRegistry registry;

	/**
	 * State variable describing if we are executing tests.
	 */
	private boolean running = false;

	private javax.swing.JButton btnRefresh;
	private javax.swing.JButton btnSearch;
	private javax.swing.JButton btnSelectAll;
	private javax.swing.JButton btnExecute;
	private javax.swing.JLabel m_executedResults;
	private javax.swing.JScrollPane m_message;
	private javax.swing.JTextArea messageArea;
	private javax.swing.JButton btnOk;
	private javax.swing.JProgressBar progressBar;
	private javax.swing.JDialog dlgTestResult;
	private javax.swing.JScrollPane m_resultScroll;
	private javax.swing.JTable tblTestResult;
	private javax.swing.JPanel m_statusBar;
	private javax.swing.JList<TestRecord> suiteList;
	private javax.swing.JScrollPane m_suiteScroll;
	private javax.swing.JTextField txtSearchTest;

	private SwingTestRegistryChangeListener registryListener;

	public SwingRunner() {
		running = false;
	}

	private void internalInitComponents() {
		initComponents();
	}

	/**
	 * Start method.
	 */
	public void start() {
		internalInitComponents();
		setVisible(true);
		dlgTestResult.setVisible(false);
		refreshSuites();
		m_executedResults.setText(" \t No executed tests");
		progressBar.setMaximum(100);
		progressBar.setValue(100);

		TableColumn column = null;
		for (int i = 0; i < tblTestResult.getColumnCount(); i++) {
			column = tblTestResult.getColumnModel().getColumn(i);
			if (i == 0) {
				column.setPreferredWidth(350); // first column is bigger
			} else {
				column.setPreferredWidth(50);
				column.setCellRenderer(new ResultCellRenderer());
			}
		}
	}

	/**
	 * Stop method.
	 */
	public void stop() {
		setVisible(false);
		dispose();
	}

	/**
	 * Refresh the list of available test suites.
	 */
	private void refreshSuites() {
		SearchPattern searchPattern = new SearchPattern(txtSearchTest.getText());
		Set<TestBean> tests = registry.getTests();

		TestListModel lm = (TestListModel) suiteList.getModel();
		lm.clear();

		for (TestBean test : tests) {
			if (searchPattern.matches(test.getName())) {
				lm.addTest(test);
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		dlgTestResult = new javax.swing.JDialog();
		m_message = new javax.swing.JScrollPane();
		messageArea = new javax.swing.JTextArea();
		btnOk = new javax.swing.JButton();
		m_statusBar = new javax.swing.JPanel();
		progressBar = new javax.swing.JProgressBar();
		btnExecute = new javax.swing.JButton();
		btnSelectAll = new javax.swing.JButton();
		m_suiteScroll = new javax.swing.JScrollPane();
		suiteList = new javax.swing.JList<TestRecord>();
		m_resultScroll = new javax.swing.JScrollPane();
		tblTestResult = new javax.swing.JTable();
		m_executedResults = new javax.swing.JLabel();
		txtSearchTest = new javax.swing.JTextField();
		btnSearch = new javax.swing.JButton();
		btnRefresh = new javax.swing.JButton();

		dlgTestResult.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		dlgTestResult.setMinimumSize(new java.awt.Dimension(320, 250));
		dlgTestResult.addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosed(java.awt.event.WindowEvent evt) {
				onDialogClosed(evt);
			}

			@Override
			public void windowClosing(java.awt.event.WindowEvent evt) {
				onDialogClosed(evt);
			}
		});

		m_message.setBorder(null);
		m_message.setMinimumSize(new java.awt.Dimension(300, 202));
		m_message.setPreferredSize(new java.awt.Dimension(300, 202));

		messageArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
		messageArea.setColumns(20);
		messageArea.setEditable(false);
		messageArea.setLineWrap(true);
		messageArea.setRows(5);
		messageArea.setWrapStyleWord(true);
		messageArea.setMinimumSize(new java.awt.Dimension(300, 250));
		messageArea.setPreferredSize(new java.awt.Dimension(250, 200));
		m_message.setViewportView(messageArea);

		dlgTestResult.getContentPane().add(m_message, java.awt.BorderLayout.CENTER);

		btnOk.setText("Ok");
		btnOk.setPreferredSize(new java.awt.Dimension(120, 23));
		btnOk.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okActionPerformed(evt);
			}
		});
		dlgTestResult.getContentPane().add(btnOk, java.awt.BorderLayout.SOUTH);

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("JUnit4OSGi Runner");
		setMinimumSize(null);
		setPreferredSize(new java.awt.Dimension(622, 657));

		progressBar.setMinimumSize(null);
		progressBar.setPreferredSize(null);

		javax.swing.GroupLayout m_statusBarLayout = new javax.swing.GroupLayout(m_statusBar);
		m_statusBar.setLayout(m_statusBarLayout);
		m_statusBarLayout
				.setHorizontalGroup(m_statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE));
		m_statusBarLayout
				.setVerticalGroup(m_statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(m_statusBarLayout.createSequentialGroup()
								.addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		btnExecute.setText("Execute");
		btnExecute.setToolTipText("Execute selected testcase/s");
		btnExecute.setMaximumSize(new java.awt.Dimension(90, 23));
		btnExecute.setMinimumSize(new java.awt.Dimension(90, 23));
		btnExecute.setPreferredSize(new java.awt.Dimension(100, 23));
		btnExecute.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				executeButtonActionPerformed(evt);
			}
		});

		btnSelectAll.setText("Select All");
		btnSelectAll.setToolTipText("Select all testcases");
		btnSelectAll.setMaximumSize(new java.awt.Dimension(90, 23));
		btnSelectAll.setMinimumSize(new java.awt.Dimension(90, 23));
		btnSelectAll.setPreferredSize(new java.awt.Dimension(100, 23));
		btnSelectAll.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				allButtonActionPerformed(evt);
			}
		});

		m_suiteScroll.setAutoscrolls(true);

		suiteList.setModel(new TestListModel());
		suiteList.setMaximumSize(null);
		suiteList.setMinimumSize(null);
		suiteList.setPreferredSize(null);
		m_suiteScroll.setViewportView(suiteList);

		m_resultScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

		tblTestResult.setAutoCreateRowSorter(true);
		tblTestResult.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		tblTestResult.setModel(new ResultTableModel());
		tblTestResult.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
		tblTestResult.setMaximumSize(null);
		tblTestResult.setMinimumSize(null);
		tblTestResult.setPreferredSize(null);
		tblTestResult.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				resultTableMouseClicked(evt);
			}
		});
		m_resultScroll.setViewportView(tblTestResult);

		m_executedResults.setPreferredSize(null);

		txtSearchTest.setToolTipText("Search your testcase by typing part of its name");

		btnSearch.setText("Search");
		btnSearch.setToolTipText("search testcase by its name");
		btnSearch.setMaximumSize(new java.awt.Dimension(90, 23));
		btnSearch.setMinimumSize(new java.awt.Dimension(90, 23));
		btnSearch.setPreferredSize(new java.awt.Dimension(100, 23));
		btnSearch.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSearchActionPerformed(evt);
			}
		});

		btnRefresh.setToolTipText("Force refresh of testcase list");
		btnRefresh.setText("Refresh");
		btnRefresh.setPreferredSize(new java.awt.Dimension(90, 23));
		btnRefresh.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRefreshActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(m_resultScroll, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
								.addComponent(m_statusBar, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(m_executedResults, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(txtSearchTest, javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(m_suiteScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 492,
														Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(btnExecute, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnSelectAll, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtSearchTest, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createSequentialGroup()
								.addComponent(btnSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnExecute, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)).addComponent(m_suiteScroll,
										javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(m_resultScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 374,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(m_executedResults, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(m_statusBar, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))));

		pack();
	}

	private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {
		if (running) {
			return;
		}
		// Collect selected test.
		int[] indices = suiteList.getSelectedIndices();
		List<TestBean> list = new ArrayList<TestBean>(indices.length);
		TestListModel model = (TestListModel) suiteList.getModel();
		for (int i = 0; i < indices.length; i++) {
			list.add(model.getTestElementAt(indices[i]));
		}
		setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
		executeTest(list);
	}

	private void allButtonActionPerformed(java.awt.event.ActionEvent evt) {
		int max = suiteList.getModel().getSize();
		int[] indices = new int[max];
		for (int i = 0; i < max; i++) {
			indices[i] = i;
		}
		suiteList.setSelectedIndices(indices);
	}

	private void resultTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_m_resultTableMouseClicked
		Point p = evt.getPoint();
		int row = tblTestResult.rowAtPoint(p);
		int col = tblTestResult.columnAtPoint(p);
		ResultTableModel model = (ResultTableModel) tblTestResult.getModel();
		String message = model.getMessage(row, col);
		if (message != null) {
			setEnabled(false);
			dlgTestResult.setTitle("Test Report");
			messageArea.setText(message);
			dlgTestResult.setVisible(true);
		}
	}

	private void okActionPerformed(java.awt.event.ActionEvent evt) {
		dlgTestResult.setVisible(false);
		setEnabled(true);
	}

	private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {
		refreshSuites();
	}

	private void onDialogClosed(java.awt.event.WindowEvent evt) {
		dlgTestResult.setVisible(false);
		setEnabled(true);
	}

	private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
		refreshSuites();

	}

	/**
	 * Execute method.
	 *
	 * @param tests
	 *            of test to execute.
	 */
	private void executeTest(final List<TestBean> tests) {
		running = true;
		btnExecute.setText("Running...");
		progressBar.setIndeterminate(true);

		ResultTableModel model = (ResultTableModel) tblTestResult.getModel();
		model.clear();

		Runnable thread = new Runnable() {
			@Override
			public void run() {

				JUnitCore core = new JUnitCore();
				core.addListener(new MyTestListener());

				for (TestBean bean : tests) {
					ClassLoader ccl = Thread.currentThread().getContextClassLoader();
					try {
						Class<?> testClass = bean.getTestClass();

						// force bundle classloader when run test
						Thread.currentThread().setContextClassLoader(testClass.getClassLoader());

						core.run(testClass);
					} catch (ClassNotFoundException e) {
						// skip test
					} finally {
						Thread.currentThread().setContextClassLoader(ccl);
					}
				}

				running = false;
				progressBar.setIndeterminate(false);
				progressBar.setMaximum(100);
				progressBar.setValue(100);
				btnExecute.setText("Execute");
				computeExecutedTest();
				setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
			}
		};
		new Thread(thread).start();
	}

	/**
	 * Compute executed tests. (Status bar message)
	 */
	private void computeExecutedTest() {
		ResultTableModel results = (ResultTableModel) tblTestResult.getModel();
		String m = " \t ";
		m += results.getTestCount() + " tests executed / ";
		m += results.getSucess() + " success / ";
		m += results.getFailures() + " failures / ";
		m += results.getErrors() + " errors ";
		m_executedResults.setText(m);
	}

	public void setRegistry(TestRegistry registry) {
		this.registry = registry;
		registryListener = new SwingTestRegistryChangeListener();
		registry.addTestRegistryListener(registryListener);
	}

	private class MyTestListener extends RunListener {
		/**
		 * Table model.
		 */
		ResultTableModel m_model = (ResultTableModel) tblTestResult.getModel();

		@Override
		public void testIgnored(Description description) throws Exception {
			m_model.addSkippedTest(description);
			adjustScroll();
		}

		@Override
		public void testAssumptionFailure(Failure failure) {
			m_model.addFailedTest(failure.getDescription(), (Error) failure.getException());
			adjustScroll();
		}

		@Override
		public void testFailure(Failure failure) throws Exception {
			if (failure.getException() instanceof Error) {
				m_model.addFailedTest(failure.getDescription(), (Error) failure.getException());
			} else {
				m_model.addErrorTest(failure.getDescription(), failure.getException());
			}
			adjustScroll();
		}

		@Override
		public void testFinished(Description description) throws Exception {
			m_model.addTest(description);
			adjustScroll();
		}

		/**
		 * Adjust the scrolling bar of the result table.
		 */
		private void adjustScroll() {
			JScrollBar bar = m_resultScroll.getVerticalScrollBar();
			if ((bar != null) && (bar.isVisible())) {
				bar.setValue(Integer.MAX_VALUE);
			}
		}
	}

	private class SwingTestRegistryChangeListener implements TestRegistryChangeListener {
		@Override
		public void registryChanged(TestRegistryEvent event) {
			TestListModel lm = (TestListModel) suiteList.getModel();
			TestBean test = event.getTest();

			switch (event.getType()) {
			case ADD:
				SearchPattern searchPattern = new SearchPattern(txtSearchTest.getText());
				if (searchPattern.matches(test.getName())) {
					lm.addTest(test);
				}
				break;
			case REMOVE:
				lm.removeTest(test);
				break;
			default:
				break;
			}
		}
	}
}